import CMSNavbar from "@/components/CMSNavbar"
import { Provider } from "../utils/Provider"
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Sanity Blog - Talha',
  description: 'Generated by Sanity Blog - Talha',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <CMSNavbar />
          {children}
        </Provider>
      </body>
    </html>
  )
}
